export type Track = "A" | "B" | "C" | "all";
export type Phase = 1 | 2 | 3 | 4;

export interface Lesson {
  slug: string;
  phase: Phase;
  week: number;
  number: string;
  title: string;
  duration: string;
  track: Track;
  free: boolean;
  description: string;
}

export const COURSE_LESSONS: Lesson[] = [
  // ── Phase 1: Foundation ───────────────────────────────────────────
  {
    slug: "introduction",
    phase: 1,
    week: 1,
    number: "Intro",
    title: "Course Introduction",
    duration: "5 minutes",
    track: "all",
    free: true,
    description: "What this program is, who it is for, the four phases, three technical tracks, and what you will build by the end.",
  },
  {
    slug: "lesson-1-1",
    phase: 1,
    week: 1,
    number: "1.1",
    title: "What Is AI, and What Is Generative AI?",
    duration: "9 minutes",
    track: "all",
    free: false,
    description: "Build an accurate mental model of AI — traditional software vs machine learning, what a model actually is, the transformer breakthrough, and where LLMs succeed and fail.",
  },
  {
    slug: "lesson-1-2a",
    phase: 1,
    week: 1,
    number: "1.2a",
    title: "From Prompts to Pipelines: The Anatomy of an AI Agent",
    duration: "10 minutes",
    track: "all",
    free: false,
    description: "What makes an AI agent fundamentally different from a chatbot. The five components every agent is built from: perception, planning, tool use, memory, and feedback loop.",
  },
  {
    slug: "lesson-1-2b",
    phase: 1,
    week: 1,
    number: "1.2b",
    title: "Inside the Machine: How LLMs Work and How to Host Them",
    duration: "12 minutes",
    track: "all",
    free: false,
    description: "What is actually happening inside an LLM — tokenisation, transformer architecture, and parameters. Cloud API vs running a model locally with Ollama.",
  },
  {
    slug: "lesson-1-3",
    phase: 1,
    week: 1,
    number: "1.3",
    title: "Real Demos: Watching Agents in Action",
    duration: "15 minutes",
    track: "all",
    free: false,
    description: "Three screen-recorded demos — a browsing agent, a coding agent, and a scheduling agent — each annotated with the five-component framework so you can see the theory in practice.",
  },
  {
    slug: "lesson-2-1",
    phase: 1,
    week: 2,
    number: "2.1",
    title: "AI Ethics and Responsibility",
    duration: "11 minutes",
    track: "all",
    free: false,
    description: "Why accountability is genuinely difficult in AI systems. The three core ethical dimensions every agent builder must engage with: privacy and consent, bias and fairness, and transparency.",
  },
  {
    slug: "lesson-2-2",
    phase: 1,
    week: 2,
    number: "2.2",
    title: "The Business of AI: How Agentic Tools Create Economic Value",
    duration: "10 minutes",
    track: "all",
    free: false,
    description: "Three industries already using agents commercially. The infrastructure vs application layer distinction. Why the barrier to building something real is domain knowledge, not technical skill.",
  },
  // ── Phase 2: Exploration ──────────────────────────────────────────
  {
    slug: "lesson-3-1",
    phase: 2,
    week: 3,
    number: "3.1",
    title: "Example Gallery: Healthcare Agents",
    duration: "14 minutes",
    track: "all",
    free: false,
    description: "Four worked agent examples from the healthcare domain — medication reminders, discharge letter decoder, school flu sentinel, and mental health check-in agent.",
  },
  {
    slug: "lesson-3-2",
    phase: 2,
    week: 3,
    number: "3.2",
    title: "Example Gallery: Research and Science Agents",
    duration: "14 minutes",
    track: "all",
    free: false,
    description: "Four worked agent examples — weekly paper digest, contradiction spotter, bibliography builder, and climate data explainer.",
  },
  {
    slug: "lesson-4-1",
    phase: 2,
    week: 4,
    number: "4.1",
    title: "Technical Track Deep Dive: Make and n8n",
    duration: "25 minutes",
    track: "A",
    free: false,
    description: "Track A deep dive. Set up your Make or n8n account, understand how no-code workflows are structured, and complete your first working trigger with at least one action.",
  },
  {
    slug: "lesson-4-2",
    phase: 2,
    week: 4,
    number: "4.2",
    title: "Technical Track Deep Dive: OpenClaw + VSCode",
    duration: "30 minutes",
    track: "B",
    free: false,
    description: "Track B deep dive. Install OpenClaw, connect to Telegram, add a domain skill, and configure your first persistent local agent.",
  },
  {
    slug: "lesson-4-3",
    phase: 2,
    week: 4,
    number: "4.3",
    title: "Technical Track Deep Dive: Agno + Python + VSCode",
    duration: "30 minutes",
    track: "C",
    free: false,
    description: "Track C deep dive. Configure VSCode with Python, install Agno, and run a working 10-line agent from your terminal.",
  },
  {
    slug: "lesson-4-4",
    phase: 2,
    week: 4,
    number: "4.4",
    title: "Project Idea Brief Workshop",
    duration: "20 minutes",
    track: "all",
    free: false,
    description: "Form your team, define your problem, and complete the six-section Project Idea Brief. Submitting the brief closes Phase 2 and opens Phase 3.",
  },
  // ── Phase 3: Build ────────────────────────────────────────────────
  {
    slug: "lesson-5-1",
    phase: 3,
    week: 5,
    number: "5.1",
    title: "Agent Architecture: Designing Before You Build",
    duration: "18 minutes",
    track: "all",
    free: false,
    description: "The five architecture questions every agent design must answer. A worked example. The most common architecture mistakes that kill student projects.",
  },
  {
    slug: "lesson-5-2",
    phase: 3,
    week: 5,
    number: "5.2",
    title: "Track Workshops: Setting Up Your Build Environment",
    duration: "30 minutes",
    track: "all",
    free: false,
    description: "Three parallel sessions — Track A, B, and C each configure their build environment for their specific project.",
  },
  {
    slug: "lesson-6-1",
    phase: 3,
    week: 6,
    number: "6.1",
    title: "Building Your First Working Prototype",
    duration: "30 minutes",
    track: "all",
    free: false,
    description: "What counts as a working prototype. The five build principles that apply to all tracks. Partial is fine. Something that runs matters more than something perfect.",
  },
  {
    slug: "lesson-6-2",
    phase: 3,
    week: 6,
    number: "6.2",
    title: "Documentation and Ethics Review (Mid-Build)",
    duration: "20 minutes",
    track: "all",
    free: false,
    description: "The mid-build ethics checklist. The six sections your project README must contain.",
  },
  {
    slug: "lesson-7-1",
    phase: 3,
    week: 7,
    number: "7.1",
    title: "Mentor Mid-Build Feedback Session",
    duration: "60 minutes",
    track: "all",
    free: false,
    description: "Course correction, unblocking, and iteration planning. Come with three specific questions, a live demo, and your biggest blocker named in advance.",
  },
  {
    slug: "lesson-7-2",
    phase: 3,
    week: 7,
    number: "7.2",
    title: "Iteration and Testing: Making It Reliable",
    duration: "20 minutes",
    track: "all",
    free: false,
    description: "The four failure types to design against. The five edge case tests every prototype must pass before final submission.",
  },
  {
    slug: "lesson-8-1",
    phase: 3,
    week: 8,
    number: "8.1",
    title: "Finalising Your Prototype",
    duration: "15 minutes",
    track: "all",
    free: false,
    description: "Make the final scope decision. Cut what is not essential. Record a compelling 3-minute demo that shows the agent working with real input.",
  },
  {
    slug: "lesson-8-2",
    phase: 3,
    week: 8,
    number: "8.2",
    title: "Project Ethics Final Review",
    duration: "15 minutes",
    track: "all",
    free: false,
    description: "Revisit every ethical decision made during the build. The four-dimension ethics rubric your submission will be assessed against.",
  },
  // ── Phase 4: Showcase ─────────────────────────────────────────────
  {
    slug: "course-closing",
    phase: 4,
    week: 10,
    number: "★",
    title: "Course Closing: Final Submission and Next Steps",
    duration: "10 minutes",
    track: "all",
    free: false,
    description: "What to submit to complete the course, the launch pathways available to you, and how to claim your certificate.",
  },
];

export const PHASES = [
  { phase: 1, name: "Foundation", weeks: "Weeks 1–2", color: "#00C4B4" },
  { phase: 2, name: "Exploration", weeks: "Weeks 3–4", color: "#4A7DFF" },
  { phase: 3, name: "Build", weeks: "Weeks 5–8", color: "#9B59B6" },
  { phase: 4, name: "Showcase", weeks: "Weeks 9–10", color: "#E67E22" },
] as const;

export const TRACKS = [
  { id: "A", name: "No-Code", tools: "Make · n8n", desc: "Students with no coding background", color: "#00C4B4" },
  { id: "B", name: "Low-Code", tools: "OpenClaw · Hermes · VSCode", desc: "Students comfortable with basic setup and configuration", color: "#4A7DFF" },
  { id: "C", name: "Full-Code", tools: "Agno · Python · VSCode", desc: "Students confident with Python or eager to learn it", color: "#9B59B6" },
] as const;
